# Site settings
title: 0xivy
description: Personal Portfolio of 0xivy


# User settings
username: 👁v
user_description: Final year student in Information Technology. Much interested in the field of Offensive Security, Networking, Web Application Security, Cloud administration etc.
user_title: Security Researcher
email: samwovian18@gmail.com
twitter_username: frozenowo
github_username:  0xivy
linkedin_username:  sam1337

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
